name: ClickOnce Deployment

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest
    
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '1.0.1' # o la versión que estés utilizando

    - name: Build and Publish ClickOnce
      run: |
        dotnet publish -c Release -o publish
        cd publish
        mage -New Deployment -ToFile MyClickOnceApp.application -FromDirectory .

    - name: Upload ClickOnce artifacts
      uses: actions/upload-artifact@v2
      with:
        name: clickonce-artifacts
        path: publish
